### PR TITLE
Changing latex syntax.

### PR DESCRIPTION
**Pull request by jonnyhtw**
HI @SMR3 😄 

Could you please review this code to check that it is doing what you wanted?

I had to change your code to get it to work for me. 

Please let me know if this doesn't make sense!

Thanks

### CODE REVIEW

**Comment by SMR3** [comment]
Hi there branchmaster :-)
Just to let you know I am trying to find my way round this stuff, but not always successfully. I can't at the moment see how to look at the changes you mention above.

**Comment by jonnyhtw** [comment]
Hi!

I think you should be able to view the code changes [here](https://github.com/jonnyhtw/gitlaboratory/pull/21/files).

I'll see if I can find out how you can pull these changes down to your machine...

Cheers 😄

**Comment by jonnyhtw** [comment]
Hi @SMR3 

The following should (!) work I think.

- Go to your local working copy of the gitlaboratory repository.

- Type `git checkout -t origin/latexsyntax`

I think you should then be able to run using my branch.

Give it a go and let me know how you get on 😄 

Cheers

**Comment by SMR3** [comment]
Hi @jonnyhtw 
Tried your suggested git checkout as above.
Got this:
fatal: git checkout: updating paths is incompatible with switching branches.
Did you intend to checkout 'origin/latexsyntax' which can not be resolved as commit?

**Comment by jonnyhtw** [comment]
Hi @SMR3 

Sorry I forgot to say that you need to a `git fetch` first I think!

- `git fetch'

- `git checkout -t origin/latexsyntax`

Does this work for you?

Cheers :smile:

**Comment by jonnyhtw** [comment]
FYI @SMR3 I got this information from [here](http://stackoverflow.com/questions/1783405/how-to-check-out-a-remote-git-branch).

Cheers!

**Pull request merged**
